app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: api_routes.yml
    type: rest
    prefix: /api/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc